spring.application.name=order-service

# Konfiguracja bazy danych
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=user
spring.datasource.password=password

# Konfiguracja Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Konfiguracja Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Port serwera
server.port=8080